### ISSUE TITLE
[Frontend] React.js Setup

### ISSUE THREAD

**Issue by lucieyang1** [Callhub-Connect/callhub-frontend#1]
- Followed this guy's YouTube tutorial: [How To Install React Js & Setup Your First Project ✅](https://www.youtube.com/watch?v=av5fmpgEJSU) 

Solutions to some issues we encountered:
- [Node.js/Windows error: ENOENT, stat 'C:\Users\RT\AppData\Roaming\npm'](https://stackoverflow.com/questions/25093276/node-js-windows-error-enoent-stat-c-users-rt-appdata-roaming-npm)
- [npm ERR! code ERR_SOCKET_TIMEOUT on creating new project using ng new appname](https://stackoverflow.com/questions/67657599/npm-err-code-err-socket-timeout-on-creating-new-project-using-ng-new-appname)
- ['npm' is not recognized as internal or external command, operable program or batch file](https://stackoverflow.com/questions/20992723/npm-is-not-recognized-as-internal-or-external-command-operable-program-or-bat)
- [How to: Add Tool Locations to the PATH Environment Variable](https://learn.microsoft.com/en-us/previous-versions/office/developer/sharepoint-2010/ee537574(v=office.14))

**Comment by MuhammadHashim06** [comment]
Hi,
I want to contribute in your Project as it open to contribute, Can you please tell me how can I participate.in your repo.
